### ISSUE TITLE
Playbook.yml

### ISSUE THREAD

**Issue by kabez** [ihassin/fruitymesh-ubuntu-vm#13]
Hi, not really much of an issue, but not everyone is familar with Vagrant and Ansible. I wasn't and it took me more than 4 days to realise that you have to edit playbook.yml to include the SDKs.

So yeah, if you cannot set it up, open up Playbook.yml and uncomment out the top three roles, and the SDK version 11, and if your using the nrf52 then the SDK for that aswell.

**Comment by ihassin** [comment]
I am so sorry! I did not realise the committed playbook had the SDKs commented out. I was debugging and removed previous steps to shorten cycle time.
I uncommented the lines in playbook.yml andI added a section in the Readme too. My apologies.
