### ISSUE TITLE
Error running "vagrant up --provider virtualbox"

### ISSUE THREAD

**Issue by anujdutt9** [ihassin/fruitymesh-ubuntu-vm#15]
Hi. I have followed all the steps as you have mentioned. When I do "vagrant up --provider virtualbox" it shows some errors like this:

Bringing machine 'fruity-vb' up with 'virtualbox' provider...
==> fruity-vb: Checking if box 'ubuntu/trusty64' is up to date...
==> fruity-vb: Clearing any previously set forwarded ports...
==> fruity-vb: Clearing any previously set network interfaces...
==> fruity-vb: Preparing network interfaces based on configuration...
    fruity-vb: Adapter 1: nat
    fruity-vb: Adapter 2: hostonly
==> fruity-vb: Forwarding ports...
    fruity-vb: 22 (guest) => 2222 (host) (adapter 1)
==> fruity-vb: Running 'pre-boot' VM customizations...
==> fruity-vb: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "3bf72288-49b8-4747-9ec8-e50ee67b7c3c", "--type", "headless"]

Stderr: VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Please if you can help me out.
Thanks : )

**Comment by ihassin** [comment]
Hi,

I cannot reproduce the error you're getting with Vagrant. Here's some of my output:

`
~/Documents/projects/infra/fruitymesh-ubuntu-vm/infra (master)$ vagrant up --provider virtualbox
Bringing machine 'fruity-vb' up with 'virtualbox' provider...
==> fruity-vb: Importing base box 'ubuntu/trusty64'...
==> fruity-vb: Matching MAC address for NAT networking...
==> fruity-vb: Checking if box 'ubuntu/trusty64' is up to date...
==> fruity-vb: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> fruity-vb: have version '20160602.0.0'. The latest is version '20161004.0.0'. Run
==> fruity-vb:`vagrant box update`to update.
==> fruity-vb: Setting the name of the VM: fruity-vb
==> fruity-vb: Clearing any previously set forwarded ports...
==> fruity-vb: Clearing any previously set network interfaces...
==> fruity-vb: Preparing network interfaces based on configuration...
    fruity-vb: Adapter 1: nat
    fruity-vb: Adapter 2: hostonly
==> fruity-vb: Forwarding ports...
    fruity-vb: 22 (guest) => 2222 (host) (adapter 1)
==> fruity-vb: Running 'pre-boot' VM customizations...
==> fruity-vb: Booting VM...
==> fruity-vb: Waiting for machine to boot. This may take a few minutes...
    fruity-vb: SSH address: 127.0.0.1:2222
    fruity-vb: SSH username: vagrant
    fruity-vb: SSH auth method: private key
    fruity-vb: 
==> fruity-vb: Setting hostname...
==> fruity-vb: Configuring and enabling network interfaces...
==> fruity-vb: Mounting shared folders...
    fruity-vb: /vagrant => /Users/ThoughtWorks/Documents/projects/infra/fruitymesh-ubuntu-vm/infra
==> fruity-vb: Running provisioner: ansible...
    fruity-vb: Running ansible-playbook...
`

It seems that your error is from Vagrant "Failed to open/create the internal network". Please see if you can bring up a simple Vagrant box with an internal net.
