### ISSUE TITLE
Failures during Provisioning

### ISSUE THREAD

**Issue by rosatolen** [ihassin/fruitymesh-ubuntu-vm#3]
1 - TASK: [common | Disable periodic OS update checks] ****************************
failed: [fruity-pvm] => {"failed": true, "rc": 257}
msg: Destination /etc/apt/apt.conf.d/10periodic does not exist !
...ignoring

2 - TASK: [fruity | See if JLink is installed] ************************************
failed: [fruity-pvm] => {"changed": true, "cmd": "dpkg -l | grep jlink", "delta": "0:00:00.025858", "end": "2015-10-07 03:17:24.849096", "rc": 1, "start": "2015-10-07 03:17:24.823238", "warnings": []}
...ignoring

Are the top two expected?

3 - `ssh deploy@fruity-pvm` does not work with the password located in the main.yml. I went in as vagrant and forcibly did `sudo passwd deploy`. Is this expected behavior?

**Comment by ihassin** [comment]
The first two are being ignored on purpose and are acceptable failures. 
Please open a new issue for the password however. Thanks!
