### ISSUE TITLE
Permissions with makefile

### ISSUE THREAD

**Issue by rosatolen** [ihassin/fruitymesh-ubuntu-vm#5]
Looks like we require `sudo` for `make clean` and `make` because of the following failure:

``` bash
makefile:34: /home/deploy/nrf/sdk/nrf_sdk_9_0/components/toolchain/gcc/Makefile.posix: Permission denied
make: stat: /home/deploy/nrf/sdk/nrf_sdk_9_0/components/toolchain/gcc/Makefile.posix: Permission denied
make: *** No rule to make target `/home/deploy/nrf/sdk/nrf_sdk_9_0/components/toolchain/gcc/Makefile.posix'.  Stop.
```

Is sudo necessary or can we change the make rules?

**Comment by ihassin** [comment]
If this is happening then something is very wrong. It means that the Ansible did not finish because one of the last things it does is change ownership. Can you send me the Ansible log file?

Ita

**Comment by rosatolen** [comment]
Yeah sure. I'll send it by email.

**Comment by ihassin** [comment]
According to the screenshots, it seems the hard-disk is corrupted. I'm sending you a link to a prepackaged box in the meantime.
